# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AMap2DMap' #2D地图SDK,
  pod 'AMapSearch' #地图搜索
  pod 'AMapLocation' #定位SDK

end
